-- Grantting users access

USER_1="user_0d_1"
USER_2="user_0d_2"
LIST_PRIVILEGES_USER_1="SHOW GRANTS FOR '$USER_1'@'localhost';"
ECHO "$LIST_PRIVILEGES_USER_1" | MYSQL -H LOCALHOST -U ROOT -P
LIST_PRIVILEGES_USER_2="SHOW GRANTS FOR '$USER_2'@'localhost';"
ECHO "$LIST_PRIVILEGES_USER_2" | MYSQL -H LOCALHOST -U ROOT -P