-- Create database
DROP DATABASE IF EXISTS HBTN_TEST_DB_7;

CREATE DATABASE IF NOT EXISTS HBTN_TEST_DB_7;

USE HBTN_TEST_DB_7;

-- Create table
CREATE TABLE IF NOT EXISTS FIRST_TABLE (
    ID INT,
    NAME VARCHAR(256)
);

-- Inserting into a table
INSERT INTO FIRST_TABLE (
    ID,
    NAME
) VALUES (
    89,
    'Holberton School'
);